### ISSUE TITLE
1.2.2 Block stun frames bug

### ISSUE THREAD

**Issue by EikaMikiku** [kosunan/MBAACC_Training#1]
In 1.2.2 blockstuns are shown to be going overboard by 6 frames:
![image](https://user-images.githubusercontent.com/8401769/168463749-6384bd36-18f5-42e3-b550-45e5aee9ebdd.png)
Image shows 1.2.1 at the top, and 1.2.2 at the bottom.
It seems like it's only a visual issue, as "Advantage -1" is same for both. So just gray visuals going over?

I used C-Len 5B to get this.

**Comment by kosunan** [comment]
Yes, it is to make it easier to know the status of the opponent when throwing....
I will think of a countermeasure.
Thanks for the bug report
