### ISSUE TITLE
[Feature Request] 'Take Control' feature?

### ISSUE THREAD

**Issue by bigorados** [kosunan/MBAACC_Training#3]
Like they have on Guilty Gear +R at Steam, dunno how hard it would be tho, maybe if taking control of the character in Replay Mode isn't possible you could develop it for you to press a key in replay mode that starts a save state > records the inputs of P1 or P2 to a dummy file of that character. I'm not a coding guy so dunno how hard this would be.
Congratulations on revolutionizing this game, love the tool, cheers.

**Comment by kosunan** [comment]
Thank you for your comment.
This tool was originally created for my own practice and only allowed save states.
I then added more features based on the Skullgirls training mode.

We would like to add as many features as possible in response to your requests.
However, no matter what method you use to learn programming, the most difficult thing is to analyze the game.
It is nothing short of a miracle that we were able to achieve the save state function.
I spent over a year on this tool, so my programming skills are not that great.

I would like to reference the ability to seamlessly transition from gear+R replay mode to training mode, but I have no plans to do so at this time.
I would like to reference this feature, but I have no plans to do so at this time.

Thank you for using this tool!
