### ISSUE TITLE
Loading state with Maids - Kohaku Lead loses you control of the character

### ISSUE THREAD

**Issue by bigorados** [kosunan/MBAACC_Training#4]
If you just switch and make a save state, when you load state you will be unable to control any of the characters.

Also this can happen if you save state mid animation: 
https://user-images.githubusercontent.com/17318774/195830220-0dea97a2-31aa-44dc-bcdd-ae97c6f70d88.mp4

**Comment by kosunan** [comment]
The above issue has been resolved.
Thank you for your report.
